tasks:
  - init: mvn install -DskipTests=false; tar xfv teamcity-inspection-notification-plugin-build/etc/tc-data.tar.gz -C teamcity-inspection-notification-plugin-build
    command: cd teamcity-inspection-notification-plugin-build; mvn tc-sdk:start