name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2.5.0
      with:
        distribution: zulu
        java-version: 11

    - name: Build with Maven
      run: mvn clean install

    - name: Test coverage Report
      run: mvn jacoco:prepare-agent test jacoco:report

    - uses: codecov/codecov-action@v2.1.0

    # Run Qodana inspections
    - name: Qodana - Code Inspection
      uses: JetBrains/qodana-action@v4.2.5

    # Collect Qodana Result
    - name: Collect Qodana Result
      uses: actions/upload-artifact@v2
      with:
        name: qodana-result
        path: ${{ github.workspace }}/qodana
