name: Deploy release

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Set pom version
        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Build with Maven
        run: mvn clean install

      - name: Upload to Jetbrains Marketplace
        run: 'curl -i --header "Authorization: Bearer ${{ secrets.TC_PUBLISH_TOKEN }}" -F pluginId=12382 -F file=@teamcity-inspection-notification-plugin-build/target/inspection-violation-notification.zip https://plugins.jetbrains.com/plugin/uploadPlugin'

